" Language
let $LANG='en'
set langmenu=en
set encoding=utf-8
set helplang=cn

" Standard Settings
set nocompatible
syntax on
filetype plugin indent on
set history=512
set clipboard=unnamed
set nobackup
set noswapfile
set viminfo='1000,f1,<500,n~/.vim/viminfo

" UI Customize
set shortmess=alI
set number
set relativenumber
set cursorline
set ruler
set showtabline=2
set laststatus=2
set cmdheight=1
set showmode
set showcmd
set showmatch
colorscheme molokai

" Search
set nowrapscan
set incsearch
set hlsearch
set ignorecase
set smartcase

" Editor
set autoindent
set smartindent
set expandtab
set tabstop=4
set softtabstop=4
set shiftwidth=4
set smarttab
set backspace=indent,eol,start
set splitbelow
set splitright

" GUI Settings
set noerrorbells
set novisualbell
set mouse=a
set guioptions=a

" Keymaps
noremap <space> <Nop>
let mapleader=" "

noremap ; :
noremap gh :noh<CR>
noremap = +
noremap + =
noremap J 10j
noremap K 10k
noremap <c-h> <c-w>h
noremap <c-j> <c-w>j
noremap <c-k> <c-w>k
noremap <c-l> <c-w>l

inoremap <c-h> <left>
inoremap <c-j> <down>
inoremap <c-k> <up>
inoremap <c-l> <right>
inoremap ( ()<left>
inoremap { {}<left>
inoremap [ []<left>
inoremap <c-a> <c-o>A

noremap <leader>ww :w<CR>
noremap <leader>wq :wq<CR>
noremap <leader>qq :q!<CR>

noremap <leader>wn :$tabnew<CR>
noremap <leader>wl :tabnext<CR>
noremap <leader>wh :tabprevious<CR>
noremap <leader>1 1gt
noremap <leader>2 2gt
noremap <leader>3 3gt
noremap <leader>4 4gt
noremap <leader>5 5gt
noremap <leader>6 6gt
noremap <leader>7 7gt
noremap <leader>8 8gt
noremap <leader>9 9gt
noremap <leader>0 10gt
